name: Check code quality on every push

on: [push]

jobs:
  cppcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install cppcheck
        run: sudo apt-get install -y cppcheck

      - name: Run cppcheck
        run: cppcheck --error-exitcode=1 src/*

  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Compile tests
        run: gcc -I src/ test/main.cpp src/*.cpp -o tests

      - name: Run tests
        run: ./tests
