name: Run cppcheck on source code

on: [push]

jobs:
  cppcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install cppcheck
        run: sudo apt-get install -y cppcheck

      - name: Run cppcheck
        run: cppcheck src/*
